### ISSUE TITLE
Reducing the grid to speed up calculations

### ISSUE THREAD

**Issue by charlotte-lemouel** [sheim/slippy#5]
It could be useful to add a line in slippy.viability.compute_Q_2D which checks whether the state-action pair is infeasable before attempting to simulate it.

**Comment by sheim** [comment]
Note, `compute_Q_2D` will very soon be deprecated in favor of the N-dimensional `compute_Q_map`.

That's a good point, although it makes things less general: infeasibility isn't something the algorithm _knows_ about. An easy hack is to just have the `step` function check this and immediately return a failure. I'll implement this ASAP since it's easy and will already speed things up considerably.

I'll leave the issue open for now, and think about if/how we should deal with this otherwise. I feel like the proper way is to have `compute_Q_map` only do the actual computation of state-action pairs, and iterate over a list of state-action pairs. Creating the grid can be done externally, which means you can set up grids however you want, leaving out infeasible points, and even have non-uniform densities... but all things that are not important or urgent.

**Comment by sheim** [comment]
Done in 8c3b0b3451d3d7b184a7bf15431b1af134a585af.
