### ISSUE TITLE
runtime error in daslip

### ISSUE THREAD

**Issue by sheim** [sheim/slippy#6]
For some initial conditions / actions, daslip runs into a runtime error:

`
/Users/heim/Repositories/slippy/slippy/daslip.py:89: RuntimeWarning: divide by zero encountered in double_scalars
  key = key -err/DerrDkey
/Users/heim/Repositories/slippy/slippy/daslip.py:353: RuntimeWarning: invalid value encountered in sin
  x[4] = x[0] + np.sin(p['angle_of_attack'])*(
/Users/heim/Repositories/slippy/slippy/daslip.py:355: RuntimeWarning: invalid value encountered in cos
  x[5] = x[1] - np.cos(p['angle_of_attack'])*(
`

Haven't really looked into it yet, will try to find state/actions that reproduce this and post it. @Matt, I'll leave this one to you since it's from the `limit_cycle` code you implemented and are most familiar with.

**Comment by sheim** [comment]
created a MWE in branch `runtime_debug` (f8e2750baf64bbafa7e55f2682c381b2d2eebb11), in the scratchpad folder, called `mwe_runtime_error.py`

**Comment by mjhmilla** [comment]
The divide by zero error will occur if a limit cycle does not actually exist for the slip model. Are regions of the state space being sampled which do not have an action that leads to a limit cycle? The answer, now that I think of the search you are doing, has to be yes. And because I'm using a limit cycle of the slip to construct the open-loop signal this causes problems.

This means one of two things:
1. We restrict the search to the set of states for which the slip has a limit cycle. Then we can just set the open-loop-signal to be the one that is appropriate for that state. That is every action in a particular state would have the same open-loop signal. Different states would get different open-loop signals. 

For nearly all actions (all but one) the open loop signal will be have a timing error. This is actually good - closer to reality. Looking at Fig. 3 of your arxiv preprint (https://arxiv.org/pdf/1806.08081.pdf) this would mean that we would lose the bottom third of the plot.

2. Or we need to re-think the way the open-loop signal is constructed. We could parametrize the function and make the parameters actions. For an open-loop signal we would have a minimum of 3 parameters: time-on, magnitude, time-off. This would add 3 actions immediately to the space.  This gets less nice fast. There are other options as well, but they were even uglier than this one.

My vote is for #1.

Reflections: I think that the daslip + realistic-damping could potentially perform worse than the slip model because now the force the leg generates is very sensitive to timing. I actually think this is a good thing, as it is closer to reality. Swing leg retraction will probably reduce these effects, but I don't know what will come out at the end. 

Despite the complications this is posing, I think the daslip might be the simplest neuromechanic model of walking in existence. That's pretty cool!

**Comment by sheim** [comment]
Aha. Okay, I'll add something to handle this so that in case a state such as this is sampled, it just returns a failure, instead of throwing an error. This way the grid continues to compute.

We definitely want to sample states where there are no LCs, but we can limit this to after the perturbation. Basically, this means we pick some operating state, fix the open-loop force to that one, and then visit states for which there are no LCs and simply use the open-loop force from the LC of the operating point. I think this fits our case well. 

This would also speed things up a bit. In my naive first implementation for the grid, for every state I solved for the LC and open-loop force of the state, which means doing quite a bit of computation for every grid point. But actually I think it makes sense to do this once, put it in the parameter dict and then go with this.

**Comment by sheim** [comment]
Now that I've written that, I'm more convinced that's the thing to do anyway.

- decide on an operating point, which will be essentially a "fixed parameter"
- compute the LC and open-loop force for that operating point, save this to the parameters
- compute the viable sets with these things fixed.

Operating points anyway **have** to be LCs _if_ we assume steady-state on the poincare section.

**Comment by mjhmilla** [comment]
That sounds good - I'm glad that approach is suitable. Being able to plot state-action space is so valuable, and this would be lost with another bunch of parameters.

**Comment by sheim** [comment]
Great, closing this.
